import { Router } from 'express';
import authRoutes from './auth';
import campaignRoutes from './campaigns';
import adRoutes from './ads';
import reviewRoutes from './reviews';
import rewardRoutes from './rewards';
import notificationRoutes from './notifications';
import redemptionRoutes from './redemption';
import analyticsRoutes from './analytics';
import anomalyRoutes from './anomalies';
import aiRoutes from './ai';
import benchmarkRoutes from './benchmarks';
import heatmapRoutes from './heatmaps';
import storytellerRoutes from './storyteller';
import teamRoutes from './teams';
import platformAccountRoutes from './platformAccounts';
import oauthRoutes from './oauth';
import attributionRoutes from './attribution';
import eventRoutes from './events';
import adminRoutes from './admin';
import billingRoutes from './billing';
import messageRoutes from './messages';
import outletRoutes from './outlets';
import supportRoutes from './support';
import siteRoutes from './site';

const router = Router();

router.use('/auth', authRoutes);
router.use('/campaigns', campaignRoutes);
router.use('/ads', adRoutes);
router.use('/reviews', reviewRoutes);
router.use('/rewards', rewardRoutes);
router.use('/notifications', notificationRoutes);
router.use('/redemption', redemptionRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/anomalies', anomalyRoutes);
router.use('/ai', aiRoutes);
router.use('/benchmarks', benchmarkRoutes);
router.use('/heatmaps', heatmapRoutes);
router.use('/storyteller', storytellerRoutes);
router.use('/teams', teamRoutes);
router.use('/platform-accounts', platformAccountRoutes);
router.use('/oauth', oauthRoutes);
router.use('/attribution', attributionRoutes);
router.use('/events', eventRoutes);
router.use('/admin', adminRoutes);
router.use('/billing', billingRoutes);
router.use('/messages', messageRoutes);
router.use('/outlets', outletRoutes);
router.use('/support', supportRoutes);
router.use('/site', siteRoutes);

export default router;
