name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    uses: ./.github/workflows/_backend.yml

  frontend:
    uses: ./.github/workflows/_frontend.yml

  mobile:
    uses: ./.github/workflows/_mobile.yml

  docker-health:
    uses: ./.github/workflows/_docker.yml

  commitlint:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_commitlint.yml
